#import "./lib/html-shim.typ": html-shim

#show: html-shim

Hi! Welcome to my site on the World Wide Web. I study (pure) math and computer
science at UC Santa Barbara (co 2028).

Here is my #link("https://github.com/youwen5")[GitHub], #link("https://www.last.fm/user/couscousdude")[last.fm], and #link("/static/img/cat_babies.jpg")[a picture of my cats].

Outside of math, I play guitar and spend way too much money on guitar pedals. I
also hate coding.

This page is generated by
#link("/luminite")[luminite], a static site generator
I wrote myself which uses #link("https://typst.app/")[Typst] as a markup
language, and Rust macros for templating. Currently I am focusing on
implementing the core of the library, and then I'll start populating this
actual site with content. See #link("/math-test")[this test] of math rendering
to the web using Typst (warning: it doesn't work very well on mobile).

For contact information, see the #link("/impressum")[impressum].
